#!/bin/bash -exu
  
CURRENT_DIR=`pwd`
echo $CURRENT_DIR > ~/.docker-xnw-dev
mkdir -p ${CURRENT_DIR}/data/{t,logs,xdebug_output} && cd ${CURRENT_DIR}/data/t
git clone ssh://git@gitlab.xnwimg.com:8044/WEB/xnw.git
cd xnw && git checkout alpha
cd ${CURRENT_DIR}
git clone ssh://git@gitlab.xnwimg.com:8044/shukebeta/docker-xnw-dev.git 
cd docker-xnw-dev && docker-compose up -d

echo '请输入你的登录密码，以允许脚本为你安装控制台脚本'

sudo cp bin/{gotoc,init-xnw-db,init-dev,init-local} /usr/local/bin 
sudo ln -s ${CURRENT_DIR}/docker-xnw-dev/bin/xnwup /usr/local/bin/xnwup
sudo bash -c 'echo -e 127.0.0.1 ddev.xnw.com org-ddev.xnw.com api-ddev.xnw.com >> /etc/hosts'
# sudo defaults write com.apple.loginwindow LoginHook ${CURRENT_DIR}/docker-xnw-dev/bin/lo0-alias
sudo ${CURRENT_DIR}/docker-xnw-dev/bin/lo0-alias

echo '现在为你添加常用git别名'
git config --global alias.st status
git config --global alias.ci commit
git config --global alias.co checkout
git config --global alias.br branch

echo 'setup 完成，接下来自动进入容器，执行初始化数据库脚本，请稍等... '
init-xnw-db
