#!/bin/bash -exu

os=`uname -s`

if [ "${os}" = "Linux" ]; then
    # 检查当前用户是否在 docker 组
    in_docker_group=`id|grep docker`
    if [ "$in_docker_group" = "" ]; then
        echo "请执行以下命令把当前用户加入到 docker 组，然后再执行本命令，加入docker组可使用以下命令："
        echo "sudo usermod -aG docker `whoami`"
        echo "重新登录并再次执行本程序可使用下面的命令(问密码时输入当前用户密码）："
        echo "su - `whoami` && ./$0"
        exit
    fi
fi

CURRENT_DIR=`pwd`

echo $CURRENT_DIR > ~/.docker-xnw-dev
mkdir -p ${CURRENT_DIR}/data/{t,logs,xdebug_output} && cd ${CURRENT_DIR}/data/t
git clone ssh://git@gitlab.xnwimg.com:8044/WEB/xnw.git
cd xnw && git checkout alpha

cd ${CURRENT_DIR}
git clone ssh://git@gitlab.xnwimg.com:8044/shukebeta/docker-xnw-dev.git
cd docker-xnw-dev

echo '请输入你的登录密码，以允许脚本为你安装控制台脚本'

if [ -f /usr/local/bin/xnwup ]; then
    sudo unlink /usr/local/bin/xnwup
fi

if [ -f /usr/local/bin/init-xnw-db ]; then
    sudo unlink /usr/local/bin/init-xnw-db
fi

if [ -f /usr/local/bin/init-local ]; then
    sudo unlink /usr/local/bin/init-local
fi

if [ -f /usr/local/bin/gotoc ]; then
    sudo unlink /usr/local/bin/gotoc
fi

sudo ln -s ${CURRENT_DIR}/docker-xnw-dev/bin/xnwup /usr/local/bin/xnwup
sudo ln -s ${CURRENT_DIR}/docker-xnw-dev/bin/init-xnw-db /usr/local/bin/init-xnw-db
sudo ln -s ${CURRENT_DIR}/docker-xnw-dev/bin/gotoc /usr/local/bin/gotoc

sudo bash -c 'echo -e 127.0.0.1 ddev.xnw.com org-ddev.xnw.com api-ddev.xnw.com >> /etc/hosts'

${CURRENT_DIR}/docker-xnw-dev/bin/init-local

# sudo defaults write com.apple.loginwindow LoginHook ${CURRENT_DIR}/docker-xnw-dev/bin/lo0-alias
sudo ${CURRENT_DIR}/docker-xnw-dev/bin/lo0-alias

echo '现在为你添加常用git别名'
git config --global alias.st status
git config --global alias.ci commit
git config --global alias.co checkout
git config --global alias.br branch

echo 'setup 完成，接下来自动进入容器，执行初始化数据库脚本，请稍等... '
sleep 5
init-xnw-db
